t1=(8,5,4,9,4,3)
t2=('green','blue','red','yellow')
len(t1)
print("Length of t1 is", len(t1))
print(max(t1))
print(min(t1))
print("Max of t1 is", max(t1))
print("Min of t1 is", min(t1))
print("Sum of t1 is", sum(t1))
print("Sorted t1 is", sorted(t1))
t2.count('red')
print("Count of 'red' in t2 is", t2.count('red'))
t2.index('yellow')
print("Index of 'yellow' in t2 is", t2.index('yellow'))